### ISSUE TITLE
Less 最佳实践

### ISSUE THREAD

**Issue by gafish** [gafish/gafish.github.com#8]
## 写在前面

在一个实验项目中用到了[ANTD](http://ant.design/)来搭建页面，为了统一技术选型，选用了ANTD所使用的LESS来写样式，总结下实践过程中比较实用的最佳实践用法。
#### 变量(Variables)

``` less
@bg: #FFFFFF;
.banner{ background: @bg; }
```

``` css
.banner{ background: #FFFFFF; }
```
#### 扩展(Extend)

``` less
.banner{ color: #FFFFFF; }
.banner .link{ color: #000000; }
.banner-channel:extend(.banner){ font-size: 14px; }
.banner-shop:extend(.banner all){ font-size: 18px; }
```

``` css
.banner,
.banner-channel,
.banner-shop { color: #FFFFFF; }
.banner .link,
.banner-shop .link { color: #000000; }
.banner-channel { font-size: 14px; }
.banner-shop { font-size: 18px; }

```
#### 混合(Mixins)

``` less
.banner{ color: #FFFFFF; }
.banner .link{ color: #000000; }
.banner-channel{ font-size: 14px; .banner(); }
.banner-shop{ font-size: 18px; .banner(); }
.banner-shop .link{ .banner > .link(); }
```

``` css
.banner { color: #FFFFFF; }
.banner .link { color: #000000; }
.banner-channel { font-size: 14px; color: #FFFFFF; }
.banner-shop { font-size: 18px; color: #FFFFFF; }
.banner-shop .link { color: #000000; }
```
#### 嵌套(Neste)

``` less
.banner {
     color: #FFFFFF;
    .link { 
        color: #000000; 
    }
}
```

``` css
.banner { color: #FFFFFF; }
.banner .link { color: #000000; }
```
#### 运算(Operations)

``` less
.banner { color: #123 + #bbb; font-size: 12px * 2}
```

``` css
.banner {  color: #ccddee;  font-size: 24px; }
```
#### 函数(Functions)

函数用法非常多，[详情点击这里](http://www.lesscss.net/functions/)

``` less
.banner {  color: color(red);  font-size: ~"100px"; }
```

``` css
.banner { color: #ff0000;  font-size: 100px; }
```
#### 命名空间(Namespaces)

``` less
.color() {
  .red { color: #f00; }
  .black { color: #000; }
}
.banner { .color > .red(); }
```

``` css
.banner { color: #f00; }
```
#### 导入(Importing)

``` less
// 导入文件（只包含文件一次）
@import "common.less";
// 导入文件，但是不添加导入的样式到编译输出中，只引用
@import (reference) "bootstrap.less";
```
#### 带参数混合

参数可以定义默认值，如没有默认值则为必填项

``` less
.border(@v; @c: #fff) { border: @v solid @c; }
.banner { .border(5px); }
.banner-channel { .border(5px, #000); }
```

``` css
.banner { border: 5px solid #fff; }
.banner-channel { border: 5px solid #000; }
```
#### 变量插值

变量可以用做选择器名

``` less
.em2rem(@name; @px){ @{name}: @px/75rem; }
.banner{ .em2rem(margin,100); }
```

``` css
.banner { margin: 1.33333333rem; }
```
#### 条件判断

``` less
.border(@px) when (@px > 10){ border: 10px solid #fff; }
.border(@px) when (@px <= 10 ) { border: ~"@{px}px" solid #fff; }
.banner { .border(5); }
.banner-channel { .border(20); }
```

``` css
.banner { border: 5px solid #fff; }
.banner-channel { border: 10px solid #fff; }
```
#### 参数拼接

arguments是所有参数的集合

``` less
.margin(@px: 1; @type: solid; @color: #fff){ margin: ~"@{arguments}"; }
.banner { .margin(5); }
.banner-channel { .margin(20, dashed, #f00); }
```

``` css
.banner { margin: 5 solid #fff; }
.banner-channel { margin: 20 dashed #f00; }
```
#### 自定义函数

``` less
@_em2rem: `(function(){
    this._em2rem = function(px){
        return px/75 +'rem';
    }
})()`;
.banner{ margin: ~`_em2rem(100)`; }
```

``` css
.banner { margin: 1.3333333333333333rem; }
```
