### ISSUE TITLE
【译】在LESS中执行JavaScript

### ISSUE THREAD

**Issue by gafish** [gafish/gafish.github.com#9]
## 译文

不久前，当我升级[LiveReload](http://livereload.com)应用时，我的一些LESS mixins开始不起作用了，在我调试的过程中，我发现一些mixins直接在LESS CSS标记中执行JavaScript代码，我不知道在LESS CSS中甚至可以这么做，也就是说Javascript可以做任何操作，于是我开始实验，至于如何使用它我还没有具体的想法，但是，我发现它是可行的。请注意，这些都是我的推测，因为没有任何关于在LESS CSS中使用JavaScript的文档（起码我没找到）。

JavaScript只能作为一项任务的部分来使用，这意味着你不能在LESS CSS中简单的执行JavaScript，相反，你必须先执行JavaScript，并且把结果分配给LESS变量或CSS属性，示例：

``` less
@foo: `javascript` ;
```

你必须把JavaScript代码写在反引号中，当你这么做时，LESS将对表达式求值并把结果以String方式返回， 如 "as is;"，它将包括引号，如果你需要移除两边的引号，可以预先使用波浪号运算符：

``` less
@foo: ~`"两边的引号将被移除"`
```

以下我提出的方案，我定义了一个"API"对象保存我的自定义函数，然后我把这个API对象注入到全局容器中，它允许这个api实例在所有其它JavaScript代码块中引用。

``` less
// 使用反引号字符在 LESS CSS 中直接运行 JavaScript
// 这里我们使用一个 Function，因为 LESS 在 function 上会调用 .toString() 方法并且保存返回值
// 当 .toString() 被调用时看起来只返回了 Functions 源码
// 这允许我们在其它 JavaScript 代码块中复用代码
@api: `function(){

    // 设置我们需要在其它 JavaScript 上下文中暴露的 API
    var api = {

        // 这只是我测试的一些 JavaScript 片断.
        getContent: function() {

            return( "This is yo' content!" );

        },


        // 当执行一个 JavaScript 表达式时，除非你在同一个 function 中，否则一次只能执行一个表达式
        // . run() 方法的意义在于它允许进入一个 function 中调用上下文， 并且在同一时间访问 API ，这个 API 作为唯一的参数被注入到给定的回调中
        // --
        // 注意: 这个回调必须返回一个值，以便LESS能够得到这个值
        run: function( callback ) {

            return( callback( api ) );

        }

    };


    // 返回这个公共 API. 由于这个 JavaScript 表达式返回父级 Function
    // 它将必须调用一个不同的 JavaScript 上下文来实际获得这个 API
    return( api );

}` ;


// 我在全局命名空间"api"中分配这个 API ，这在前面的 JavaScript 代码中可以实现，但是我喜欢把它分拆到各自负责的区域
// --
// 注意：在这里我用了一个自调用 function ，有助于保证 this 指向全局上下文，并且不会是计算的上下文（假如它们是不同的）
@apiGlobalInjector: `(function() {

    // 注入API并将它存储在全局对象
    this.api = (@{api})();

    // JavaScript 必须返回一些 LESS CSS 可以分配给变量的值
    return( "Injected in global" );

})()` ;


// ---------------------------------------------------------- //
// ---------------------------------------------------------- //


h1 {
    content: `api.getContent()` ;
}

h2 {
    content: `api.run(function( api ) {
        return( api.getContent().toUpperCase() );
    })` ;
}
```

当你执行一个 JavaScript 块, LESS CSS 似乎不喜欢分号，除非你是在一个 function 中使用，像这样，我创建了一个 .run() 方法，它只是一种创建自注入 API 的方法，如此，你可以运行多个实例并且返回一个值

无论如何，当你运行编译上面的文件， LESS CSS 会输出以下这些:

``` css
h1 {
    content: "This is yo' content!";
}
h2 {
    content: "THIS IS YO' CONTENT!";
}
```

像我之前所说的，我不能完全确定我将如何使用它，但是，它肯定能满足你的想像力，不出意外，它会激发我更多关于 LESS CSS 框架的学习。

---
## 原文

[Executing JavaScript In The LESS CSS Precompiler](http://www.bennadel.com/blog/2638-executing-javascript-in-the-less-css-precompiler.htm)

The other day, when I upgraded my LiveReload app, some of my LESS mixins started to break. During the debugging process, I discovered that some of the mixins were executing JavaScript code directly in the LESS CSS markup. I had no idea that this was even possible in LESS CSS; and so, as with all things JavaScript, I had to start experimenting. I have no concrete ideas on what I would use this for; but, here's what I found. Please note that this is all conjecture as there is zero documentation (that I could find) on the use of JavaScript in LESS CSS.

JavaScript can only be evaluated as part of an assignment. By this I mean that you can't simply execute JavaScript in LESS CSS. Instead, you have to execute the JavaScript and then assign the result to a LESS variable or a CSS property. Example:

``` less
@foo: `javascript` ;
```

To denote JavaScript, you have to wrap your code in backticks. When you do this, LESS will evaluate the expression and return the result as a String. It does so, "as is;" meaning, it leaves all your quotes in-place. If you want to remove the surrounding quotes, you can prepend the tilde operator:

``` less
@foo: ~`"surrounding quotes will be removed"`
```

That said, here's what I came up with. I defined an "API" object that holds my user-defined functions (UDFs). I then inject this API object into the global container which allows the "api" instance to be referenced in all the other JavaScript code blocks:

``` less
// Use the backtick character to run JavaScript directly in LESS CSS. We are using a
// Function here because LESS calls (my theory) .toString() on the function and stores
// the return value. It seems that only Functions returns their "source code" when
// .toString() is called, which allows us to reuse the JavaScript in other JavaScript
// code block instances.
@api: `function(){

    // Set up the API that we want to expose in other JavaScript contexts.
    var api = {

        // This is just me testing some JavaScript stuff.
        getContent: function() {

            return( "This is yo' content!" );

        },


        // When executing a JavaScript expression, you can only execute one expression
        // at a time (ie, no semi-colons). Unless, you are in a function. The point of
        // the run() function is to allow the calling context a way to enter a function
        // context and get access to the API at the same time. The API is injected as the
        // only argument to the given callback.
        // --
        // NOTE: The callback MUST RETURN A VALUE so that LESS can get the value of it.
        run: function( callback ) {

            return( callback( api ) );

        }

    };


    // Return the public API. Since this JavaScript expression is return the parent
    // Function, it will have to invoked in a different JavaScript context to actually
    // get access to the API.
    return( api );

}` ;


// I assign the API the global namespace, "api". This could have been done in the
// previous JavaScript code block; but, I kind of liked the idea of breaking it out into
// its own rsponsability.
// --
// NOTE: I am using a self-invoking function here to help ensure that "this" points to
// the global context and not to the context of the evaluation (if its different).
@apiGlobalInjector: `(function() {

    // Inject the API and store it in the global object.
    this.api = (@{api})();

    // The JavaScript HAS TO RETURN something so LESS CSS can assigne the variable value.
    return( "Injected in global" );

})()` ;


// ---------------------------------------------------------- //
// ---------------------------------------------------------- //


h1 {
    content: `api.getContent()` ;
}

h2 {
    content: `api.run(function( api ) {
        return( api.getContent().toUpperCase() );
    })` ;
}
```

When you execute a JavaScript block, LESS CSS doesn't seem to like semi-colons; unless you are in side of a function. As such, I created a .run() method, which was just a way to create a function that self-injects the API. This way, you could run multiple statements and return a value.

Anyway, when you run the compile the above file, LESS CSS produces the following output:

``` css
h1 {
    content: "This is yo' content!";
}
h2 {
    content: "THIS IS YO' CONTENT!";
}
```

Like I said before, I am not exactly sure how I would use this yet; but, it definitely tickles the imagination. If nothing else, it's inspired me to learn more about LESS CSS as a framework.
